### ISSUE TITLE
Add Instructions on how to respond to Facebook's Free Basics form

### ISSUE THREAD

**Issue by rdsubhas** [netneutrality/savetheinternet.in#100]
The home page shows Email instructions. It would be nice if we can also include screenshots of Facebook's sly free-basics form that is being shown to millions of people.

http://www.huffingtonpost.in/2015/12/17/facebook-free-basics_n_8824378.html

**Comment by miteshashar** [comment]
@rdsubhas Where are you suggesting us to show the screenshots?

**Comment by rdsubhas** [comment]
@miteshashar thanks for the great work. If you could add a page on how to respond to Facebook's "I support Free Basics" form, and probably link to it in the home page it would be great :+1: And we can share that link in our social network for people to take the right action if facebook shows that form

**Comment by miteshashar** [comment]
The best way to respond to it is not to respond to it. Whatever you do, they will show people you support Free Basics.

**Comment by rdsubhas** [comment]
yeah that's definitely true :+1: thanks
