### ISSUE TITLE
SMT. Meenakshi lekhi - NCT - New Delhi

### ISSUE THREAD

**Issue by Rajeev0507** [netneutrality/savetheinternet.in#108]
meenakashi.lekhi@sansad.nic.in

**Comment by miteshashar** [comment]
That is one of the listed email address on the Lok Sabha website. Is the email to her gmail account getting through?

**Comment by miteshashar** [comment]
Duplicate for: #106

**Comment by miteshashar** [comment]
https://github.com/netneutrality/savetheinternet.in/issues/106#ref-commit-85893c5

**Comment by Rajeev0507** [comment]
Yes, email to gmail account was going through.

--- Original Message ---
