### ISSUE TITLE
Dharam Vira Gandhi

### ISSUE THREAD

**Issue by sahilgoyal786** [netneutrality/savetheinternet.in#111]
Delivery to the following recipient failed permanently:

     dvgandhi@yahoo.com

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain yahoo.com by mta7.am0.yahoodns.net. [98.138.112.38].

The error that the other server returned was:
554 delivery error: dd This user doesn't have a yahoo.com account (dvgandhi@yahoo.com) [-5] - mta1053.mail.ne1.yahoo.com

**Comment by knightsamar** [comment]
The right email address according to http://myneta.info/ls2014/candidate.php?candidate_id=7853 is dvgandhi1951@yahoo.com and I have tested it just now. A PR is on the way.

**Comment by miteshashar** [comment]
Solved in https://github.com/netneutrality/savetheinternet.in/commit/626b6d5a9d211527a8928825d11bc8e4b607e712
