### ISSUE TITLE
Save The Internet: glitch in email text

### ISSUE THREAD

**Issue by pgonline** [netneutrality/savetheinternet.in#12]
Hi folks,

Firstly, great job of taking the initiative. I am happy to see that the country still has hope!

Coming to the problem, in the email, the following text appears everywhere in the body where a new line should be:
%0D%0A%0D%0A

This makes the email very unreadable and as texty as the stupid TRAI  doc.

I accessed the site using my samsung galaxy grand handset. 
Android version: 4.2.2

Kindly resolve this at the earliest.

Suggestion:
If the users find a glitch in the system, half of them just close the window without completing the process. The other half who do want to make a change decide to register a complaint. Now, that link brings us to this site. 
Again, users cant register a complaint without an account. By this time most of the users lose their patience and a few jobless people like me actually manage to reach this stage.
(The mobile version of this site doesnt even have a sign up button!)

Hence I request you to please find a better way for  people to register their complaints.

Thank you again for taking this initiative. 

Hope we win!

Warm regards,
Prateek Gupta

**Comment by gargsms** [comment]
@pgonline Also, just asking, does the email text contain all of the 20 questions?

**Comment by pgonline** [comment]
Yes. That is ok.
Just sort the new line problem and we are good to go.

**Comment by gargsms** [comment]
Actually there shouldn't be a problem to start with. The browser __must__ send the text in proper format.
Can you provide more details about your browser, email client etc?

**Comment by pgonline** [comment]
I use chrome on my mobile handset running on android v 4.2.2.

I use gmail.

**Comment by aravindet** [comment]
@pgonline Good point regarding github sign ins. Sometimes we forget that everyone is not on Github. We're switching to a google form in the next 5 minutes.

Are any other special characters mangled? Do you see any % symbols followed by 2 digits other than 0D or 0A?

**Comment by pgonline** [comment]
Awesome! Google forms is a great idea.

No other text apart from what I have already mentioned: %0D%0A%0D%0A

Yes the % sign is visible.

**Comment by karthikb351** [comment]
@aravindet This is explicitly encoded, it's fix for iOS devices. But right now it's for all mobile. I'll change it to only iOS useragents.

**Comment by karthikb351** [comment]
@pgonline Can you check if it's fixed? Check on stage-savetheinternet.herokuapp.com

**Comment by pgonline** [comment]
There persists here as well!

**Comment by pgonline** [comment]
The problem persists here as well!

**Comment by pgonline** [comment]
![screenshot_2015-04-11-22-06-26](https://cloud.githubusercontent.com/assets/11900478/7102239/9e8c1458-e097-11e4-8751-0cf4cd438115.png)

**Comment by karthikb351** [comment]
@pgonline can you check now? - http://stage-savetheinternet.herokuapp.com

**Comment by pgonline** [comment]
Same story! 

Wot device are you testing on?

**Comment by karthikb351** [comment]
Nexus 5, 5.1 lollipop.

Looks like a long night ahead :(

**Comment by gargsms** [comment]
@pgonline Can you check if [this] (mailto:asdf@example.com?subject=FML&body=I%20hope%20this%0Aworks!) works?

I don't have an Android phone but I tried in a VM running ICS. For me both %0D%0A and only %0A works.

**Comment by pgonline** [comment]
I hope this%0Aworks!

This is wot im getting

**Comment by gargsms** [comment]
Dang! Life is hard. :disappointed: 
Weird anomalies all around.

**Comment by pgonline** [comment]
Ok guys. Some good news!

I did some research and realised that the issue could be due to the browser itself.
I found out that google released some major updates on chrome browser.
I just updated the same. Its working perfectly now. :-)

So it was Google's fault not urs! :-|

Anyway, is there a way to warn people about this? Am pretty sure not everyone updates their apps thanks to the limited internal memory on smartphones.

**Comment by gargsms** [comment]
Wut!@pgonline By the way, you can create a Wiki page as a contribution if you want. :)

**Comment by pgonline** [comment]
That is a good idea!
However, I don't know if I will be able to do justice to it as I just got to know about this issue through AIB's video.

I need to do some research before making one! May do it tomorrow of possible! #Sunday :-D

**Comment by miteshashar** [comment]
@pgonline confirmed the issue is resolved and was due to an issue in Chrome's older version.
