### ISSUE TITLE
Smt. Meenakashi Lekhi

### ISSUE THREAD

**Issue by veeru1saini1** [netneutrality/savetheinternet.in#121]
Delivery to the following recipient failed permanently:

     meenakashi.lekhi@sansad.nic.in

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain sansad.nic.in by mailgw.nic.in. [164.100.10.19].

The error that the other server returned was:
550 #5.1.0 Address rejected.mail address(es) here…

**Comment by miteshashar** [comment]
Duplicate of #106

**Comment by miteshashar** [comment]
https://github.com/netneutrality/savetheinternet.in/issues/106#ref-commit-85893c5
