### ISSUE TITLE
Please enter the name of the MP here

### ISSUE THREAD

**Issue by karthikkhadke** [netneutrality/savetheinternet.in#122]
To,

Shri B. Sreeramulu

Member of Parliament, Bellary (ST)

Respected Sir,

It has been nine months since over 12 lakh Indian Internet users wrote to the TRAI in favour of Net Neutrality. Over 450 Internet Startups wrote to the Prime Minister for his support in ensuring that the telecom industry and Facebook not to gain control over the Internet by controlling what users access. It has also been five months since thousands of Internet users, in response to a Department of Telecom committee report on Net Neutrality, registered on the Prime Minister’s MyGov.in website, asking the government of India to support Net Neutrality.

In spite of such large scale support for Net Neutrality, including that from many of you in Parliament:

* Telecom operators continue to launch services that violate Net Neutrality, by offering free access to services that they prefer or have tie-ups with.

* Facebook continues to offer and aggressively promote its Free Basics (Internet.org) service, which gives a competitive advantage to Facebook and its partners. The Free Basics service will colonise the Indian startup ecosystem by making Facebook a gatekeeper and the kingmaker for any online website or application.

* The Department of Telecom has not published an amended report considering the clear opposition in responses on MyGov.in to all forms of zero rated services. There has been no notice on how and when it will do so and at present there is a level of uncertainty and confusion which is being caused by some stakeholders by rolling out services which violate net neutrality.

At the same time, telecom operators are partnering with Facebook to run Net Neutrality violating services like Internet.org/Free Basics. These services are aggressively expanding without due respect for the sanctity of ongoing regulatory processes. It is relevant to mention that the DOT draft report in Para 12.7 and 12.8 calls for a complete prohibition specifically on Internet.org. Completely ignoring the spirit of these regulatory processes Facebook has been using its large user base on Facebook with automated popups and campaigns to misinform and mislead Indian users into sending responses favouring Internet.org/Free Basics.

The issue of Net Neutrality is an issue of Internet Freedom, and of the independence of Internet access in India from the control of large oligopolies. The Internet as it is accessed today is the fundamental reason for the progress and innovation we have seen online over the past 15 years. Net Neutrality means that a telecom operator or ISP cannot give competitive advantage to their favoured Internet companies, and therefore will provide a fair opportunity for the development of India’s startup ecosystem and innovative solutions to the economic and social needs of our country.

We endorse the idea of providing “all of the Internet, to all of the people, all of the time”, put forth by the World Wide Web foundation and various international organisations, such as Mozilla, which are seeking to further access without compromising net neutrality. It is our belief that the goals of access and net neutrality are incredibly important for India and the TRAI can further them both without coming at the cost of either. Access and net neutrality are too important to be put into a binary exchange.

As a member and a voter in your constituency, I urge you to please raise your voice in support of Net Neutrality in Parliament, and ask the government to take urgent action by:

1. Putting a moratorium on services such as Internet.org/Free Basics until the governments policy is finalised. We believe and agree with the TRAI that it has adequate jurisdiction to ensure net neutrality through tariff regulation measures. These measures must be exercised urgently, in the interim to prevent widespread breaches that are being done in the absence of binding rules.

2. Asking for the TRAI to choose in favour of Net Neutrality and submit its report before the budget session of Parliament in 2016.

3. A commitment by the Department of Telecom to publish a firm timetable with actionable steps for the introduction of a net neutrality law in India. A firm timetable and consultation process will improve predictability and trust in the consultation framework. It is our fear that despite the TRAI acting in our best interests, certain stakeholders may rely on the earlier consultation, or recommendations following the consultation to instill ambiguity and prevent firm and clear regulations.

Thanking you.

**Comment by miteshashar** [comment]
@karthikkhadke There are two emails listed for Mr. Sreeramulu: b.sreeramulu@sansad.nic.in, sreemulu070@gmail.com.
Are you facing an issue sending an email to any of these addresses?
I am closing the issue for now, since no details have been provided about failure of sending an email. Please feel free to reopen the issue with more specific details.
