### ISSUE TITLE
Karnataka – Bangalore South : Shri Ananth Kumar

### ISSUE THREAD

**Issue by ad-a-hoc** [netneutrality/savetheinternet.in#123]
You have received this notification, as the recipient e-mail Address has been deactivated.

Original Envelope Sender: axxxxxxxs@gmail.com
Envelope Recipient: akumar-alpha@sansad.nic.in
Date: 12/25/15
Time: 20:47:07
Subject: Seeking your support for Net Neutrality in Parliament

Message Administrator

**Comment by miteshashar** [comment]
So, you have received this for the sansad.nic.in email address?
Are you able to get through the other email address(ananth@ananth.org)?

**Comment by ad-a-hoc** [comment]
ananth@ananth.org didn't get any bounce mail, it got delivered somewhere!
