### ISSUE TITLE
There is no mention of anything related to net-neutrality anywhere on the website what

### ISSUE THREAD

**Issue by amarendra** [netneutrality/savetheinternet.in#125]
Or what is at stake here regardint current Facebook plans, or something like Airtel Zero. 

At least a page where other sources, videos can be linked, would be quite useful for people who are visiting the site.

PS. I recommended the site to a friend who asked what netneutrality is and he told me that the site just asks him to send an email is all.

**Comment by miteshashar** [comment]
Added a link to the STI blog in the footer.
