### ISSUE TITLE
Include freebasics domain

### ISSUE THREAD

**Issue by runningmark** [netneutrality/savetheinternet.in#126]
TRAI has issued another consultation paper asking once again, if we want Net Neutrality. This time, it's about differential pricing - Airtel Zero and Internet.org type services.
Include it as people would think it is wrong there is internet.org not freebasics

**Comment by miteshashar** [comment]
@runningmark The context of your issue is not clear. Hence, I am closing it. Thanks.

**Comment by captn3m0** [comment]
I think @runningmark was pointed at the use of `internet.org` in the copy:
>Airtel Zero and Internet.org type services.

And whether we should use `freebasics.com`there instead.

**Comment by miteshashar** [comment]
Done: 412c7be
