### ISSUE TITLE
Email contents missing

### ISSUE THREAD

**Issue by gvkalra** [netneutrality/savetheinternet.in#129]
Hi,

When I am trying to send an email from my mobile, the email application doesn't get full contents.

Browser: Chrome on Android
Email Application: Inbox (by Gmail)

PFA screenshot of how it appears.
![screenshot_2015-12-26-14-28-04](https://cloud.githubusercontent.com/assets/498380/12005795/359fb244-abdd-11e5-9e1e-7e47009a48a2.png)

**Comment by knightsamar** [comment]
Please give version details of Chrome, Android and Inbox.

**Comment by gvkalra** [comment]
![screenshot_2015-12-26-22-29-44](https://cloud.githubusercontent.com/assets/498380/12007216/a257688a-ac20-11e5-857c-6b019474ec8c.png)
![screenshot_2015-12-26-22-31-44](https://cloud.githubusercontent.com/assets/498380/12007217/b2b5de46-ac20-11e5-86d9-d5591740583e.png)
![screenshot_2015-12-26-22-32-16](https://cloud.githubusercontent.com/assets/498380/12007225/d2b355a2-ac20-11e5-97ec-0a77860b9d17.png)

**Comment by gvkalra** [comment]
@knightsamar I attached screenshots of the version information. It's always reproducing in my device. If I can help you with some logs, let me know how to take it.

**Comment by miteshashar** [comment]
@gvkalra @knightsamar It's reproducing on my mobile too. But, still not gotten around to the cause. If any of you do, please please throw in a pull request.

**Comment by gvkalra** [comment]
I guess it's something to do with specifics of Inbox.

I uninstalled Inbox, tried sending the mail with GMail and it worked.

**Comment by miteshashar** [comment]
For me it works on Gmail even if I do not uninstall Inbox, which I have not tried.

**Comment by gvkalra** [comment]
@miteshashar you mean for you GMail is problematic?

I am confused by
"It's reproducing on my mobile too"
and
"For me it works on Gmail even if I do not uninstall Inbox, which I have not tried."

**Comment by miteshashar** [comment]
Sorry about the confusion.

"It's reproducing on my mobile too. But, still not gotten around to the cause. If any of you do, please throw in a pull request."
was a response to your comment: "It's always reproducing in my device. If I can help you with some logs, let me know how to take it."

"For me it works on Gmail even if I do not uninstall Inbox, which I have not tried."
was a response to your comment: "I uninstalled Inbox, tried sending the mail with GMail and it worked."

:)

**Comment by miteshashar** [comment]
@cliveverghese Thanks. I dont think that would solve the problem. Moreover, since you closed the PR subsequently, I presume you realised the same.
