### ISSUE TITLE
Inactive Email address - Karnataka – Bangalore South : Shri Ananth Kumar

### ISSUE THREAD

**Issue by augiwan** [netneutrality/savetheinternet.in#130]
akumar-alpha@sansad.nic.in

---

**FROM: Mail Notification <MAILER-DAEMON@esadel04.nic.in>**
**SUBJECT: Inactive ID Notification.**

You have received this notification, as the recipient e-mail Address has been deactivated.

Original Envelope Sender: augustus.***@gmail.com
Envelope Recipient: akumar-alpha@sansad.nic.in
Date: 12/26/15
Time: 14:35:51
Subject: Seeking your support for Net Neutrality in Parliament

Message Administrator

---

**Comment by miteshashar** [comment]
Duplicate #123
