### ISSUE TITLE
Please spread this

### ISSUE THREAD

**Issue by bheema-bhx** [netneutrality/savetheinternet.in#133]
Some cellular companies sending messages like below.

ఫేస్‌ బుక్‌ ద్వారా ఫ్రీ బేసిక్స్‌ సేవ అందరికీ అవసరమైన ఇంటర్‌ నెట్‌ సేవ ఉచితంగా అందించబడుతుంది. ఐతే ఈ సేవల పై ఆంక్షలు విధించే అవకాశం ఉంది. దయచేసి 1800 209 0921 కి మిస్డ్‌ కాల్‌ చేసి, మాతో సహకరించండి

"Facebook and the Internet service to everyone in the free Basics service is provided free of charge. However, it is possible to impose restrictions on these services. Please Missed Call 1800 209 0921 to, and collaborate with us"

It is against the Net Neutrality, So Don't give any missed call to above number.

**Comment by miteshashar** [comment]
Thanks @bheema-bhx. I have shared your comment on social media.
