### ISSUE TITLE
Shri Dilip Kumar Mansukhlal Gandhi

### ISSUE THREAD

**Issue by sakshishukla** [netneutrality/savetheinternet.in#135]
Hi,

We dont want net neutrality proposed by facebook.
Kindly check this issue.

Thanks,
sakshi

**Comment by knightsamar** [comment]
Hi @sakshishukla, what is the exact issue you are facing ? Please paste the error message if that was an email delivery failure.

**Comment by miteshashar** [comment]
@sakshishukla Thanks for taking the effort to register to leave this comment here. This space is meant for reporting issues with the savetheinternet.in website.
We asked you to post an issue here only in the case of not being able to reach your MP's listed email on the site.
To send the email to your MP, you can simply follow the instructions on the link http://www.savetheinternet.in/mp
