### ISSUE TITLE
Shree Krishan Pal Gurjar

### ISSUE THREAD

**Issue by mandeeprawat** [netneutrality/savetheinternet.in#137]
palkrishangurjar@gmail.com - Wrong email.

**Comment by miteshashar** [comment]
@mandeeprawat Did you receive any Delivery Notification Failure email? Kindly share further details.

**Comment by mandeeprawat** [comment]
Sorry, we were unable to deliver your message to the following address.

<palkrishangurjar@gmail.com>:
Remote host said:
550-5.1.1 The email account that you tried to reach does not exist. Please try
550-5.1.1 double-checking the recipient's email address for typos or
550-5.1.1 unnecessary spaces. Learn more at
550 5.1.1  https://support.google.com/mail/answer/6596 v202si10078454qka.80 - gsmtp
[RCPT_TO]
