### ISSUE TITLE
No trai email addess

### ISSUE THREAD

**Issue by gagan97** [netneutrality/savetheinternet.in#14]
Please provide trai email id also on page, because when I'm filling up form on mobile on clicking send response it taking me to my email client but doesn't fill the destination address so basically I don't have the email id where I need to post this mail

**Comment by karthikb351** [comment]
Could you provide some more information on your OS/Browser?

**Comment by manuganji** [comment]
This happened to me on iPad.

**Comment by gagan97** [comment]
This happened with chrome and Google inbox on xiaomi mobile but it worked with similar configuration and yahoo mail app so I guess Gmail inbox is the culprit here. If u need any help to debug or log please let me know. I'll try to do my best

**Comment by ishansharma** [comment]
Google Inbox issue will be fixed in latest released.
