### ISSUE TITLE
2-click flow for almost all users

### ISSUE THREAD

**Issue by aravindet** [netneutrality/savetheinternet.in#140]
On most mobile platforms, we have ideal workflow requiring only two clicks:

- Click the button, which launches the system email app with the email pre-filled.
- Click "Send".

This covers about 70% of our users.

On desktop people typically do not have mailto: handlers set up, so we’re using the rather cumbersome Copy-Paste flow.

However most users have webmail, so instead of a single button we can show desktop users several buttons: "Email TRAI using your Gmail", "Email TRAI using your Yahoo" etc. Clicking them will open the service with the email pre-filled, and the user just hits submit just like on mobile.

Most webmail providers these URLs that act as mailto: handlers, for example:

- GMail: https://mail.google.com/mail/?extsrc=mailto&url=%s
- Yahoo: https://compose.mail.yahoo.com/?To=%s

where %s is to be replaced with a URL-encoded mailto: link (containing to, bcc, subject and body).

We cannot do this with IE unfortunately (URL length limit), which means we have to use copy-paste flow for them.

**Comment by jace** [comment]
There's a body length limit here as well, which is why we added the copy paste workflow. Gmail, for instance, truncates text beyond a certain number of chars (don't remember limit).

**Comment by aravindet** [comment]
Yeah, true. The URL length limit for the GMail mailto handler is 4kb (and they seem to have a separate (load-balancer level?) limit of 10kb.)

Our email is around 23 kb so it won't work.
