### ISSUE TITLE
Shri Kodikunnil Suresh Email is Invalid

### ISSUE THREAD

**Issue by riginoommen** [netneutrality/savetheinternet.in#147]
Hey 
Email of Shri Kodikunnil Suresh, Member of Parliament, Mavelikkara (SC) is invalid and getting the failure acknowledgment message 

Email - kodikunnilsuresh@yahoo.co.in

**Comment by miteshashar** [comment]
@riginoommen What is the reason of failure mentioned in the Delivery Failure Notification email?

**Comment by riginoommen** [comment]
Email is incorrect

**Comment by riginoommen** [comment]
Delivery to the following recipient failed permanently:

     kodikunnilsuresh@yahoo.co.in

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain yahoo.co.in by mx-apac.mail.gm0.yahoodns.net. [106.10.166.52].

The error that the other server returned was:
554 delivery error: dd This user doesn't have a yahoo.co.in account (kodikunnilsuresh@yahoo.co.in) [-5] - mta1096.mail.sg3.yahoo.com

**Comment by riginoommen** [comment]
Delivery to the following recipient failed permanently:

     kodikunnilsuresh@yahoo.co.in

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain yahoo.co.in by mx-apac.mail.gm0.yahoodns.net. [106.10.166.52].

The error that the other server returned was:
554 delivery error: dd This user doesn't have a yahoo.co.in account (kodikunnilsuresh@yahoo.co.in) [-5] - mta1096.mail.sg3.yahoo.com
