### ISSUE TITLE
Typo: 'misrepresented' spelled as 'misprepresented'

### ISSUE THREAD

**Issue by palerdot** [netneutrality/savetheinternet.in#154]
I have also created a pull request for this

https://github.com/netneutrality/savetheinternet.in/pull/153

**Comment by miteshashar** [comment]
Fixed in ddca6db

**Comment by palerdot** [comment]
Thanks,

But he typo is still there in the actual blog posts which does not come from this github repo
http://blog.savetheinternet.in/if-youve-been-misled-by-facebook/

You may have to rectify it.
