### ISSUE TITLE
Anto Antony

### ISSUE THREAD

**Issue by jeffrey4u** [netneutrality/savetheinternet.in#161]
For the email address(es) that have bounced, please provide us the following by copy-pasting it from the Failure Delivery email that you have received:
• Failed email address: 
anto.antony@ymail.com

• Technical details:
Google tried to deliver your message, but it was rejected by the server for the recipient domain ymail.com by mta7.am0.yahoodns.net. [98.138.112.34].

• The error that the server returned:
554 delivery error: dd This user doesn't have a ymail.com account (anto.antony@ymail.com) [0] - mta1285.mail.ne1.yahoo.com

**Comment by miteshashar** [comment]
@jeffrey4u http://nocorruption.in/mps/anto-antony/#_ lists the other email address as invalid too. Did that bounce?

**Comment by jeffrey4u** [comment]
No, only this email email id bounced- anto.antony@ymail.com
