### ISSUE TITLE
Organizing a response

### ISSUE THREAD

**Issue by CxRes** [netneutrality/savetheinternet.in#163]
I am writing here because I do not know how to reach specific savetheinternet.in volunteers.

I would like to volunteer my time to organize a counter-response to TRAI consultation paper responses by cellular operators and their collectives. But it is something I cannot do alone. So I was wondering if the community can split up the work to respond to a operator each and then cross-check our responses before putting them out. Unlike other organizational or industry response this could be a true civil society response...

**Comment by jace** [comment]
You've come to the right place. Can we have your email address?

**Comment by CxRes** [comment]
`q7957-trai-petition@yahoo.co.in`
(I started using the alias because of the TRAI leak last time, but now I find it helps with organizing mails as well :) )

May I suggest/request having a 'sitemap' and 'contact us' on the savetheinternet webpage for others looking to help out...

**Comment by jace** [comment]
Check your mail.
