### ISSUE TITLE
Any plans to target BSNL/MTNL for injecting ads on customer's computers? 

### ISSUE THREAD

**Issue by Sushubh** [netneutrality/savetheinternet.in#164]
I understand that FreeBasics is the current focus of this platform. But I would like you guys to consider expanding the scope a bit to include MTNL and BSNL for their behavior of injecting ads on customer's devices. 

I posted a thread on reddit highlighting the issue: 
[MTNL and BSNL Broadband are both injecting ads on their internet services pretending it is a feature](https://www.reddit.com/r/india/comments/408ceq/mtnl_and_bsnl_broadband_are_both_injecting_ads_on/)

This is essentially a MITM attack by the ISP. And they are pretending that it is a feature aimed at helping their customers. Peace.

**Comment by jace** [comment]
We're _currently_ limiting our focus to having TRAI pass rules because it's hard enough to stay focused on one thing (and _not_ Free Basics, which is collateral impact). However, if TRAI does pass favourable rules, the remaining things like ISPs modifying pages in transit become plainly illegal and easier to target.

However, if you'd like to take this up on priority, you're welcome to volunteer. We are after all a bunch of volunteers doing this in our spare time.

**Comment by clain4u** [comment]
Dear BSNL,

    Injecting data (Ads) in the requested information, which means you are altering the information.
    You are collecting my:
        Machine details
        Browser Details
        OS Information
        My usage pattern
        And my location
        All of that, without my approval or knowledge which means you are spying on my web browsing.

    You are collecting all my personal data for your own financial benefits.

    You are breaching my Privacy by collecting my search & behavior pattern.

    These ads are affecting my speed of access which I pay for.

Hence its vital that you remove the ads before we approach the court.

**Comment by avinashseth** [comment]
I'm from MP, and i still get these ads, are you guys done with them or still facing that issue ?

**Comment by clain4u** [comment]
I have lodged a complaint to the BSNL office and the ads seems to have
disappeared. So only the baby that cries gets the milk..!! Try the same..
lodge a complaint


*ThanksClain D'silva*

**Comment by avinashseth** [comment]
hi you mean some forum they have or i've to actually visit them and lodge the complaint ?

**Comment by clain4u** [comment]
Visit BSNL office and lodge a complaint.. Its easy and you will get it
resolved


*ThanksClain D'silva*
