### ISSUE TITLE
Bug in sub heading of http://blog.savetheinternet.in

### ISSUE THREAD

**Issue by RaghavPro** [netneutrality/savetheinternet.in#169]
This is weird.
Here's the header code from http://blog.savetheinternet.in
```
<div class="main-header-content inner">
    <h1 class="page-title">Save the Internet</h1>
    <h2 class="page-description">India’s fight for Net Neutrality</h2>
</div>
```

And this is how it renders
![screen shot 2016-01-24 at 22 47 54](https://cloud.githubusercontent.com/assets/4872139/12537760/f791fe54-c2ec-11e5-80da-06f470430d6b.png)
No F in fight.

The problem is in `font-weight` property of `page-description`.

I'm using OSX 10.11.1 and this happens on latest versions of Safari, Firefox and Chrome.

**Comment by captn3m0** [comment]
Same for me on OSX 10.11.1 + Chrome atleast. Guessing an issue with the Merriweather?

**Comment by captn3m0** [comment]
Looks like its a bug in the `fi` ligature in the Merriweather font update: https://github.com/google/fonts/issues/8#issuecomment-174155822

**Comment by davelab6** [comment]
The update to Merriweather was made in advance of the Firefox 44 launch on Tuesday that will mean the old files will just stop working. 

The bug with fi/fl ligatures has a workaround - you can turn ligatures off with CSS to work around this until then:

    -webkit-font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;
    -moz-font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;
    -o-font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;
    font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;

**Comment by miteshashar** [comment]
@davelab6 I checked that this does get solved if we change `font-weight: 400;` to `font-weight: bold;`.
This may not be the ideal solution but works, is trivial and lets us focus on more important things right now.
Anyways, feel free to fork & send us a PR on what you feel is the best solution. Though, this bug is technically not a part of this repo. It should be on https://github.com/netneutrality/blog.savetheinternet.in

**Comment by davelab6** [comment]
If you do nothing, it will be fixed upstream with Google in about 24 hours

**Comment by miteshashar** [comment]
@davelab6 Ah, perfect! Thanks for the heads up.
