### ISSUE TITLE
[Suggestion] Use multiple responses to prevent TRAI from considering all the mails sent to them as spam.

### ISSUE THREAD

**Issue by vijayant123** [netneutrality/savetheinternet.in#22]
TRAI might consider all the same mails it receives  as spam. You could choose random responses for each questions from these set of favorable responses: 

http://bit.ly/altresponse 

http://bit.ly/BestOneYetJU 

http://bit.ly/ndtvott

http://bit.ly/juresponse

You could take these answers and choose randomly from them.

**Comment by ishansharma** [comment]
Thank you. We are working on shuffling the answers already. Will forward your to team.
