### ISSUE TITLE
Why Bcc?

### ISSUE THREAD

**Issue by hvgirish** [netneutrality/savetheinternet.in#26]
What is the purpose of having the bcc to one of your email-ids by default? 

You quote 'You will be able to edit before you send. We also send ourselves a copy so that we can verify that your response is acknowledged by TRAI'. How is the verification done?

I ask because I think this is evil. The default behaviour must be to _not_ include the Bcc and suggest the users to opt-in to add it.

**Comment by karthikb351** [comment]
There is no way for us to keep track of exactly how many submissions unless we bcc ourselves, since we are getting users to send it from their own accounts. We don't send it on their behalf

**Comment by hvgirish** [comment]
I understand the limitation. But to just track the number of users, we are getting personal email-ids from a lot of people which I think is not good. Why not add a dialog-box that asks 'Did you send the email - we need this to just track the overall number of emails sent', Yes, count++. That would be more accurate too, since even people who opt to not bcc, will also be counted accurately.

**Comment by jace** [comment]
If TRAI claims they did not receive your email -- which is extremely likely since DoT has used this excuse in the past -- we now have proof that they are lying. MediaNama is coordinating this.

**Comment by jace** [comment]
The majority of visitors to the site are on mobile. Once they send the email, they go back to their email inbox, not to the website.

The privacy conscious can always edit before sending, since nothing is sent automatically. We built defaults for users who didn't want to look into the details.

**Comment by hvgirish** [comment]
MediaNama, the name, gives me no confidence. You really want those email-ids for future use. Fair enough.
Maybe a check-box to opt-in? Anyway, upto you guys. Personally, I am not too fond of privacy as such. Was just watching out for you because some ppl might throw a fit. I got interested with tracking the number, because, displaying the number in real-time would give such a kick for others to join in.

Cheers. Happy sifting-through-emails-in-gmail to have a count. ;)
