### ISSUE TITLE
Suggestion to link other platforms like Change.org etc. on the website.

### ISSUE THREAD

**Issue by Ritvik1512** [netneutrality/savetheinternet.in#28]
I strongly recommend linking other platforms like Change.org on the website, so that we can channelize the movement in some way or other.
Also, I'm working on an alternative to the popup window, that is a bit laggy on some mobile devices. Will post a fix soon.

**Comment by asdofindia** [comment]
We have netneutrality.in with a lot of links. Too many links on savetheinternet.in might distract people. But it might be a good idea to send people off to netneutrality.in after they send the email.

**Comment by Ritvik1512** [comment]
Alright sweet.
