### ISSUE TITLE
Highlighting the necessary sentences 

### ISSUE THREAD

**Issue by suj009** [netneutrality/savetheinternet.in#39]
Once the person clicks "Send your response" button, There is a pop-up with Q&A and later a small section providing instructions on "How to send the email". From my point of view, this information is very important for the person to see first and get his mind clear rather than the whole Q&A which is already written. Also, the sentence which points out "The response has been copied into your clipboard" and the instructions on how to proceed next has to be highlighted in bold and explained clearly. I literally rushed through and was about to send an email which out message. I know it's my mistake of not reading through instructions, but I'm sure there are many people like me, who will rush through information without reading.

**Comment by jace** [comment]
We've changed the workflow so that copying is not automatic. You have to copy to clipboard manually (the site will ensure you copy the full thing). We'll go live after a bit more testing since there's a lot of traffic on the site and small issues will blow up.

**Comment by suj009** [comment]
From my understanding, the previous approach was easy and efficient. But needs a clear instruction and aligning. In this approach, a user needs to just paste the Q&A which is already copied automatically. But in the new workflow, you are allowing users with manually copy the Q&A, which increases one step from the previous version. But with this workflow also, the problem of user ending with empty content is not solved I believe. So you could make the user stop doing that problem by restricting them to that section or page, like without copying the Q&A or performing some action or proving a pop-up message saying "have you performed these actions", the user can't progress to next section.

**Comment by jace** [comment]
That's exactly how it works. Earlier people didn't notice that they had to paste. Now they can't proceed until they copy, so it's clearer that they need to paste.

**Comment by suj009** [comment]
That's, perfect. But I feel people might get confused still at last phase. so here is my proposed solution. 

![screen shot 2015-04-12 at 12 45 48 pm](https://cloud.githubusercontent.com/assets/5426006/7105449/e3358dda-e111-11e4-999f-ac7e6e3b8faf.png)
