### ISSUE TITLE
Telugu translations for the text

### ISSUE THREAD

**Issue by manuganji** [netneutrality/savetheinternet.in#43]
Save the internet. Tell TRAI we need network neutrality.

ఇంటర్నెట్ ని కాపాడండి. మనకి నెట్వర్క్ తటస్థత అవసరం అని ట్రాయ్ (TRAI ) కి  చెప్పండి.

-----------------------

This page has the best arguments that favour net neutrality in India, written as a response to the TRAI consultation paper. The deadline for submission is 24th April 2015.

ఈ పేజీ ట్రాయ్ సలహా పేపర్ కి సమాధానంగా రాయబడింది . ఇందులో భారతదేశం లో ఇంటర్నెట్ తటస్థత కి అనుకూలంగా ఉత్తమ వాదనలు ఉన్నాయి. సమాధానాలు పంపించడానికి ఆఖరి తేది 24 ఏప్రియల్ 2015.

-----------------------

You may choose to submit the response we've generated or edit the responses and submit your own version.

మీరు మేము రాసిన సమాధానాన్ని యధాతధంగా పంపించవచ్చు లేదా మీ వాదనలతో మీ స్వంత ప్రతిని పంపవచ్చు.

-----------

send your response

మీ స్పందన పంపండి

--------------

Submit response

ప్రతిస్పందనను పంపండి

------------
The response has been copied to your clipboard

Compose an email and paste this response using Right-click->Paste or Ctrl/Cmd+V

ఈ జవాబు మీ క్లిప్ బోర్డుకి  కాపీ చేయబడింది

ఒక ఇమెయిల్ మొదలుపెట్టి right click చేసి -> Paste నొక్కండి లేదా Ctrl + V లేదా మాకింటోషులో Command + V ఉపయోగించి ఈ జవాబు ని జోడించవచ్చు

--------

Emails should be sent to advqos@trai.gov.in. Please bcc us at netneutralityindia@gmail.com

You will be able to edit before you send. We send ourselves a copy so that we can verify that your response is acknowledged by TRAI.

ఇమెయిళ్ళను advqos@trai.gov.in పంపాలి. దయచేసి netneutralityindia@gmail.com ని bcc లో పెట్టండి 

మీరు పంపడానికి ముందు సవరణలు చెయ్యవచ్చును. మేము మీ స్పందన TRAI చే గుర్తించబడిందని ధ్రువీకరించడానికి ఒక కాపీని అడుగుతున్నాము.

**Comment by anandology** [comment]
Neutrality is called "తటస్థత"  in telugu, not "మధ్యస్థత".

**Comment by manuganji** [comment]
I got that as the first suggestion in Google Translate but I thought that sounds a little too technical for people to grasp. I wonder which word has been adopted by the media though. For now, I replace it with తటస్థత :)

**Comment by manuganji** [comment]
Is this going to be used at all? Do you need any more information?
