### ISSUE TITLE
A summary of the entire response

### ISSUE THREAD

**Issue by paramv** [netneutrality/savetheinternet.in#45]
It might be helpful if the response to the TRAI consultation paper is summarized in bullet points, probably as a new button/collapsible div. This would prevent people from being overwhelmed by the size of the response. While it is true that one should not submit the response without reading it in its entirety, it would help to explain terms like "net-neutrality","OTTs" etc and bullet points how this could adversely affect end users, so those who are not familiar with the issue will have some context before reading the response.

**Comment by asdofindia** [comment]
This is what we're trying to do with [netneutrality.in](http://netneutrality.in). It is linked to from this site.

**Comment by miteshashar** [comment]
Should be taken care of by #51
