### ISSUE TITLE
Add a couple trackers to homepage to show participation

### ISSUE THREAD

**Issue by vyder** [netneutrality/savetheinternet.in#47]
Problem: Right now, although the main page is informative and is clear on the action(s) a visitor is expected to take, it does not indicate how many people have already emailed them or shared/like the page etc.

Potential Solution: How about writing a little script that keeps track of the number of emails you receive by bcc and shows it on the website? This makes it more interactive, and helps the issue snowball more. E.g. I'm more likely to watch a YouTube video if I know 5 million people have already seen it than if it only has like 400 views.

I can totally help code this up if you guys decide you want to implement it.

**Comment by asdofindia** [comment]
We already have a script that counts the emails sent (and it was well above 20,000 last night itself :D). It'll soon be added to the site.

**Comment by vyder** [comment]
Nice! Looking forward to seeing it.
