### ISSUE TITLE
Better alternative flow to editing answers

### ISSUE THREAD

**Issue by srikanthlogic** [netneutrality/savetheinternet.in#51]
Edit answers is useless on mobile.  content editable doesnt work (Chrome / Android). should we hide them on mobile ? , its a regression, works on master.. stage has an issue

mitesh [1:31 PM] 
I think the editing part can be handled much better. We need to shift away from the contenteditables

**Comment by asdofindia** [comment]
Can't edit the answers on Firefox for Android, Safari on iPhone.

**Comment by knightsamar** [comment]
Ok. Let's just tell mobile users, _specifically_ they can edit the responses in their Compose window.

**Comment by karthikb351** [comment]
Can we close this?
cc @miteshashar
