### ISSUE TITLE
Encourage users to write a message themselves

### ISSUE THREAD

**Issue by indradhanush** [netneutrality/savetheinternet.in#59]
Problem: Sending the same message could be useless as TRAI might think its only a handful of people using different email addresses. 

Solution: Explain the consequences of net neutrality violation and how it can affect any regular individual, and tell them why they should preferably write about it in their own words.

**Comment by miteshashar** [comment]
The answers are now randomised, @indradhanush.
The aware & more proactive netizens always have the last-mile option to read and edit their emails before they hit 'Send'.
