### ISSUE TITLE
Add a share to Facebook button!!

### ISSUE THREAD

**Issue by wowitsmrinal** [netneutrality/savetheinternet.in#6]
Add a share to Facebook button!!

**Comment by pravj** [comment]
Hi @wowitsmrinal,

There is a share to Facebook button but it appears once you are done with the emailing.
In the `Thank You` section there, you can also see a Tweet option too.

I second you if you're talking about having a social share portal on the landing page to just share the link on social platforms.

What do you think about this @karthikb351?
There is a [jQuery plugin](https://github.com/iatek/jquery-share) which covers a lot of social platforms.

**Comment by karthikb351** [comment]
@pravj We wanted to know the count of shares as well, which Socialite.js does.
