### ISSUE TITLE
Deadline seems to May 8th as per TRAI instead of April 24th.

### ISSUE THREAD

**Issue by Vadi** [netneutrality/savetheinternet.in#60]
Not sure "deadline" means in the home page. Would be able to provide pull request, if people are busy here.

![image](https://cloud.githubusercontent.com/assets/218148/7105105/4692a71a-e125-11e4-8a6f-fa322713a4b6.png)

**Comment by asdofindia** [comment]
The deadline for sending comments is April 24. May 8 deadline is for counter comments. We'll probalby need another campaign for that :D

**Comment by Vadi** [comment]
You're right. Closing it. We will need another issue to come up with counter comment approach.
