### ISSUE TITLE
AdBlockPlus blocking popups

### ISSUE THREAD

**Issue by srikanthlogic** [netneutrality/savetheinternet.in#62]
ABP blocking popups. 

1. Add note to disable ABP?
2. Can we avoid popups??

**Comment by knightsamar** [comment]
No issue on Firefox 37.0.1 on Lollipop on Moto G 2. Didn't need to disable for the site.

**Comment by suj009** [comment]
no issues on chrome too.

**Comment by shrayasr** [comment]
No issue on Firefox 37.0.1 on OSX 10.10.1

**Comment by gargsms** [comment]
No issues. Firefox 38, Firefox Nightly 41 on Ubuntu 14.04.
What popups are you talking about anyway?

**Comment by karthikb351** [comment]
Can we close this @srikanthlogic ?

**Comment by srikanthlogic** [comment]
@karthikb351 Reported this from feedback spreadsheet. Think we can.
