### ISSUE TITLE
Show counter in Home page for how many visits and emails sent

### ISSUE THREAD

**Issue by ermauliks** [netneutrality/savetheinternet.in#63]

**Comment by ermauliks** [comment]
I can pick this up, if anyone can guide me about accessing the numbers? Do we've access to it? cc @miteshashar @asdofindia

**Comment by karthikb351** [comment]
@ermauliks Most of the data we get is deferred. Mails get delivered late, and GA doesn't give us live numbers.

We'll get back to this once we have a more reliable system for stats.

**Comment by miteshashar** [comment]
@ermauliks For now you can follow Bulletin Babu on https://twitter.com/bulletinbabu

**Comment by miteshashar** [comment]
@karthikb351 This is technically still open. Isn't it?

**Comment by karthikb351** [comment]
We could just leave it parked. But I thought we discussed that we wouldn't have a counter on the site for performance reasons. Not mention the addition traffic that will come just to see the counter(which is great, but we don't need unnecessary traffic :P)

**Comment by ermauliks** [comment]
@karthikb351 makes sense. Now we don't need to motivate people anymore ;)

**Comment by miteshashar** [comment]
(Y)
