### ISSUE TITLE
On mobile only part of the response gets copied into Inbox on Android

### ISSUE THREAD

**Issue by kartikluke** [netneutrality/savetheinternet.in#7]
**How to replicate:**
1. Share on a phone.
2. Open in Inbox.
3. Only half the email gets through.

**Comment by jace** [comment]
What phone, browser and mail client? Android+Chrome+Gmail and iOS+Safari+Mail work.

**Comment by karthikb351** [comment]
And also perhaps let us know where exactly it's getting cut off?

**Comment by kartikluke** [comment]
HTC One. Android. Inbox by Gmail. Around the 11th question.

**Comment by kartikluke** [comment]
Picture for reference.

**Comment by kartikluke** [comment]
Possibly there's a limit on body length you can pass through a mailto. I've heard of wonkiness in the number of characters accepted in this regard.

**Comment by karthikb351** [comment]
@kartikluke can you try again at https://stage-savetheinternet.herokuapp.com/ ?

**Comment by kartikluke** [comment]
![screenshot_2015-04-11-20-50-16](https://cloud.githubusercontent.com/assets/3857139/7101931/eea4eef2-e08c-11e4-8137-a55cc384d4d3.png)

Remains the same. Seems to be Inbox specific. Works on Gmail.

**Comment by karthikb351** [comment]
It's breaking at the the `=` at the following line.
`a recent study [http://dl.acm.org/citation.cfm?id=2700055]`
That's an encoding issue I can't reproduce here.
Will look into this.

**Comment by jace** [comment]
Some encoding issue related to the `=` that appears there.

Maybe we should wrap it in bitly.

**Comment by jace** [comment]
@karthikb351 just wrap the link for now?

**Comment by karthikb351** [comment]
On it.

**Comment by gargsms** [comment]
Shouldn't the body be encodeURIComponent'ed instead of replacing just the newline?
It will handle everything by itself.
=  should be %3D

**Comment by karthikb351** [comment]
@gargsms Yeah, that's what I did and pushed to the stage server, doesn't help

**Comment by miteshashar** [comment]
This issue has been reported as closed.

**Comment by kartikluke** [comment]
Hello!
Your friend Kartik S. recently e-filed taxes on ClearTax -- and wants to recommend ClearTax to you for your tax return filing.

I'll give you a little bit of context on ClearTax: India's largest tax platform with over a million Indian tax payers and 20,000 businesses. E-Filing is secure and free on our platform.

    - If you receive a Form-16, just upload it here - http://email.cleartax.in/wf/click?upn=2383OvSW-2BdRJaftD-2Fy6Xl4MKZ1XcRgbuXx-2BnXHXEwpFFiXIumsC59z1sCf1l0Ksq_s5UH8bhnBaopYjthcNSRcV8FpWWz8vEoCBvN46dxVLBf9Ts8iZI2ObmaaHwUEueHH7NNvkHrLRvw9ZaTiYL5-2By1UOn4X57yqk2kcP917pWb-2BKYOuX30tUuxV-2BOj9T3ugJr87W-2BAZRJ-2Bi5ySVOpSbrQzt1w84-2Fwo-2BOCL-2FB2-2B6PQ-2FxkZPeeSj6vA4t7G7M-2Bpd9CkTdCvTIqBzSzS4Yf50Q-2FMf0HPJJleY6ABQIhxX7UM3ioiFJoHBFvhMLtHo-2B2nepxxgkEse1iPHnNvSzestbM9-2BwCTtdIOZYTXTzeqSdL3UAr9De9NA5qvITeKPO3GiZ2-2Fr0Kry-2FwGr9Ecjew7eFQot9o6-2FDqC5ngdj-2BCBhSEkYDBthsmoxTQwSl3bDr-2BCw9 and automatically all details will be filled for you.
    - We support all income types from Indian residents, NRIs, Freelancers and Businesses.
    - We partner with large corporations, public banks and state Governments for customers and employees.

We would love to help you with your e-Filing. Here's the invitation referral link - http://email.cleartax.in/wf/click?upn=2383OvSW-2BdRJaftD-2Fy6Xl4MKZ1XcRgbuXx-2BnXHXEwpFFiXIumsC59z1sCf1l0Ksq_s5UH8bhnBaopYjthcNSRcV8FpWWz8vEoCBvN46dxVLBf9Ts8iZI2ObmaaHwUEueHH7NNvkHrLRvw9ZaTiYL5-2By1UOn4X57yqk2kcP917pWb-2BKYOuX30tUuxV-2BOj9T3ugJr87W-2BAZRJ-2Bi5ySVOpSbrQzt1w84-2Fwo-2BOCL-2FB2-2B6PQ-2FxkZPeeSj6vA4t7G7M-2Bpd9zdN1kQnmZBqrp3xu4xef2aESCooGFC4TnnZxsDWnG9OHYk8n83nK51s0TXFkQEC1rIoieE5G3w8-2BS0BmrKrtS28Ecy7mjM-2FN3vSKXbs5X6i5zTKgoH2bnOdZTWfqTQ-2Fep7om8EqkcCgbfVkemEWj6wS0YmS6ZE-2BBOLbW-2FGQXe6F3Tpk9c6Hll4-2FcUqG-2BEeLy

Best,
Neha, Head Customer support, ClearTax

PS: Economic Times and NDTV ranked ClearTax as the best tax platform in India.

**Comment by kartikluke** [comment]
Hello!
Your friend Kartik S. recently e-filed taxes on ClearTax -- and wants to recommend ClearTax to you for your tax return filing.

I'll give you a little bit of context on ClearTax: India's largest tax platform with over a million Indian tax payers and 20,000 businesses. E-Filing is secure and free on our platform.

    - If you receive a Form-16, just upload it here - http://email.cleartax.in/wf/click?upn=2383OvSW-2BdRJaftD-2Fy6Xl4MKZ1XcRgbuXx-2BnXHXEwpFFiXIumsC59z1sCf1l0Ksq_s5UH8bhnBaopYjthcNSRcV8FpWWz8vEoCBvN46dxVLBf9Ts8iZI2ObmaaHwUEueHH7NNvkHrLRvw9ZaTiYL5-2By1UOn4X57yqk2kcP917pWb-2BKYOuX30tUuxV-2BOj9T3ugJr87W-2BAZRJ-2Bi5ySVOpSbrRQmfuFBjaK7EocznQecKdGMgIUSKuE-2FksjKVLBqrDic40yDQqal7ymBJziSiTYZfx-2FMT66ShWQmBZmM-2BWCd9tlQcUKH9q2jRJzk5en-2F5qAd1rH-2FVnai92foBnJUyt-2F73AQyDlcL4KucOPbR-2BvKhL-2BgMIqwrgVHeIUfzHzqEW9KuqRTLzybhzD92XTUd-2FAe5tLPhaFbti5mY27F7ubncHgFFNUzLVFYcjAoxgKON7i-2FA and automatically all details will be filled for you.
    - We support all income types from Indian residents, NRIs, Freelancers and Businesses.
    - We partner with large corporations, public banks and state Governments for customers and employees.

We would love to help you with your e-Filing. Here's the invitation referral link - http://email.cleartax.in/wf/click?upn=2383OvSW-2BdRJaftD-2Fy6Xl4MKZ1XcRgbuXx-2BnXHXEwpFFiXIumsC59z1sCf1l0Ksq_s5UH8bhnBaopYjthcNSRcV8FpWWz8vEoCBvN46dxVLBf9Ts8iZI2ObmaaHwUEueHH7NNvkHrLRvw9ZaTiYL5-2By1UOn4X57yqk2kcP917pWb-2BKYOuX30tUuxV-2BOj9T3ugJr87W-2BAZRJ-2Bi5ySVOpSbrRQmfuFBjaK7EocznQecKdGMgIUSKuE-2FksjKVLBqrDicVQ5l2KxfgfFodEB8TeHUI9tiSUK3wPWqoeXL5s5CvawceQM3wTmtkf4nwmc8Tw9kpDq4nDa1o-2B9f-2BkRmQTvv0Y2UKl5DjEHz5HYIwEGCZAk3NYFBJanjCzVNwoITkAyRpwzb1n1g3VaJR2VBtx80711VaiOAgQbXkBteo8lwy-2FUtjhwqekmWopBQwbg8nQXS

Best,
Neha, Head Customer support, ClearTax

PS: Economic Times and NDTV ranked ClearTax as the best tax platform in India.
