### ISSUE TITLE
Social media sharing links (Possibly using Addthis or similar tool)

### ISSUE THREAD

**Issue by thepegasus** [netneutrality/savetheinternet.in#84]
It will be logical to place social media sharing links in the homepage possibly using Addthis (http://www.addthis.com/) or a similar tool. Importance should be given to sharing on twitter, FB and Linkedin. A sample can be seen in the page http://www.addthis.com .

**Comment by miteshashar** [comment]
Thanks @thepegasus. We do have social media sharing tools using socialite. They are shown after one sends the email.
