### ISSUE TITLE
Reduce the number of CTA buttons!

### ISSUE THREAD

**Issue by akshaytyagi** [netneutrality/savetheinternet.in#89]
There are two many CTA buttons. There are two report buttons which are in the same color as the main "Respond to TRAI" button, and an additional button linking to Github.

I think the primary button should be green, there should be only one report button, and the report and GitHub buttons should be less prominent. Consider making them a light shade of gray. They should probably be just links instead of buttons.

I think this will make the site simpler.

![cta sti](https://cloud.githubusercontent.com/assets/992983/7164791/615db2fe-e3c0-11e4-969a-792596a256c9.PNG)

**Comment by menatankush** [comment]
+1
I agree with @akshaytyagi

**Comment by karthikb351** [comment]
It is a bit much. I agree.

cc: @jace

**Comment by menatankush** [comment]
index.new.html version looks good on Mobile devices, just little bit formatting changes required. (Y)
![screenshot_2015-04-15-23-08-55](https://cloud.githubusercontent.com/assets/9079960/7165385/0f18f3c8-e3c5-11e4-8a9b-7aaa9654e6d2.png)

**Comment by jace** [comment]
This one is too heavy for our current traffic level, so we moved it out to the related site `netneutrality.in`.
