### ISSUE TITLE
Send response button not working.

### ISSUE THREAD

**Issue by abhihimself** [netneutrality/savetheinternet.in#9]
"Send response button" seems to be disabled on the website. Please look in to the issue.

**Comment by jarsj** [comment]
The one on the bottom after clicking "Edit Answers" doesn't work on Firefox. The one on the top works.

**Comment by karthikb351** [comment]
Could you provide some more details? Browser/Operating System?

**Comment by jarsj** [comment]
Firefox 37, Mac OS.

**Comment by jarsj** [comment]
1) Click "Edit Answers".
2) Scroll Down.
3) Click on the top side (Top-30%) of Send Button. It doesn't work.
4) Clicking on the bottom side works.

**Comment by aravindet** [comment]
@abhihimself Does it look different? Could it be a gray plugin missing icon? Could you send a screenshot? Thanks!

@jarsj thanks we'll try to reproduce this.

**Comment by asdofindia** [comment]
This is because the flash plugin is active on the upper part and not active on the lower. See screenshot.
![screenshot from 2015-04-11 19 36 45](https://cloud.githubusercontent.com/assets/945777/7101679/57510d88-e082-11e4-97ae-54b7b05ca3eb.png)

**Comment by miteshashar** [comment]
Issue will be resolved in an upcoming release.
