### ISSUE TITLE
Improved copy

### ISSUE THREAD

**Issue by akshaytyagi** [netneutrality/savetheinternet.in#91]
A lot of the language on the STI page is convoluted and repetitive. I have simplified it a bit. Consider using it.

![sti](https://cloud.githubusercontent.com/assets/992983/7216927/ea4a1c2c-e62e-11e4-96d4-c704a45dfb73.PNG)

Plain text of the new copy:

>Save the open internet. Tell TRAI we need net neutrality
>Respond to TRAI now or edit your answers (email to advqos@trai.gov.in and a copy to us)
>This page is a collection of the best arguments that can be made in favour of net neutrality, in the >framework of the TRAI consultation paper.
>
>It's purpose is to assist supporters of net neutrality in articulating their own views on the matter in a >legally precise manner, in order to submit a response to the TRAI before the deadline on 24 April >2015.
>
>Appeal to politicians: keep this campaign apolitical.
>
>You can do a lot more to further the cause with just a little effort. We have a lot of ideas and are >eager to hear yours!
>
>Get involved »
>
>
>For more information on why Net Neutrality is important, visit netneutrality.in
>
>Made with ♥ by folks just like you Report a technical problem

**Comment by shrayasr** [comment]
:+1: from me. I like the simplicity here.

**Comment by karthikb351** [comment]
This has become an obvious issue.
cc: @jace and @atnixxin can we do a rewrite?

**Comment by jace** [comment]
Good to merge.
