### ISSUE TITLE
TRAI email screw up

### ISSUE THREAD

**Issue by akshaytyagi** [netneutrality/savetheinternet.in#95]
I almost made a comment here suggesting STI send all mails on people's behalf by anonymising people's IDs by doing something along the lines of the MaskMe tool. This would also make the submission process simpler by not making people leave the site.

I don't know why, but I had a feeling that exactly this was going to happen. This is why I used my public email id instead.

These people don't understand the Internet and want to regulate it!

Anyway, we should try to avoid this in the future on our end.

**Comment by aravindet** [comment]
This is TRAI's mistake and they should be fixing it on their end. We cannot send emails on peoples' behalf for obvious credibility reasons.

**Comment by sarsarahman** [comment]
@akshaytyagi : How would one will send mail on others behalf? thats totally illogical and also if you mask the ID how would you prove the authenticity of the petitioner? Its totally fault of TRAI.
