### ISSUE TITLE
Adding jshint to Grunt tasks

### ISSUE THREAD

**Issue by sohamkamani** [netneutrality/savetheinternet.in#96]
Linting all the javascript would prevent silly errors from getting in the way of making an awesome website, and make sure all the js code is up to mark before anyone commits anything. Also would make the website easier to scale and improve.

I have already started working on adding jshint to default grunt task and fixed a few errors thrown by it. Thoughts?

**Comment by sohamkamani** [comment]
... just realized this might be a little out of date :sweat:

**Comment by karthikb351** [comment]
That's okay, send a PR anyway @sohamkamani
