### ISSUE TITLE
Localisation needed

### ISSUE THREAD

**Issue by karthikb351** [netneutrality/savetheinternet.in#99]

**Comment by avckp** [comment]
Hi,
I have translated the page /index.html to hindi. You can view it [here] (https://github.com/avckp/savetheinternet.in/blob/stage/src/hi/index.html). But i haven't translated the letter completely yet and its in english still. The language is a bit terse and its taking time. Depending on the last date for sending emails I will continue with the task of translating , is it 31st or 7th? I suppose it won't be of any use if its completed by tomorrow and last date being 31st.

**Comment by miteshashar** [comment]
The last date is 30th, i.e. tomorrow.
We cannot launch unless the answers are completely translated too, else there is no point as people will not have the freedom to read, understand and edit their answers.
@jitendravyas @avckp Do you think you can pull it off soon?
A request, please use simple hindi language, as a lot of people might not be able to understand complex or less frequently used words. See my comments on https://github.com/netneutrality/savetheinternet.in/pull/146

**Comment by avckp** [comment]
Its great what you guys have done so quickly. Unfortunately I am at work and not able to contribute . I have requested my friend to translate the letter. He will send pull request once done.
